[package]
name = "mmd2jsx"
version = "0.1.4"
edition = "2024"

[lib]
name = "mmd2jsx"
path = "src/lib.rs"

[dependencies]
encoding_rs = "0.8"      # Shift JIS デコード
clap = { version = "4", features = ["derive"] }  # CLIオプション解析
glam = "0.29"

[lints.rust]
future-incompatible = "warn"

[lints.clippy]
all            = { level = "warn", priority = -1 }
clone_on_copy  = "deny"
redundant_clone = "deny"
